<center>
<p style="font-size: 60px;"><b>Pandas Book</b></p>
</center>

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\uih30853\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\users\uih30853\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\uih30853\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\uih30853\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\uih30853\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\uih30853\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

<center>
    <h1>
        <b>1. Pandas Foundations</b>
    </h1>
</center>

<h2>DataFrame and route</h2>

<h4>Route</h4>

In [3]:
movie = pd.read_csv(r"C:\Users\uih30853\OneDrive - Aumovio SE\Desktop\movie.csv")

<h4>DataFrame</h4>

In [4]:
movie.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

<h4>DataFrame Attributes <b>(index, columns and values)</b></h4>

In [5]:
index = movie.index
index

RangeIndex(start=0, stop=4916, step=1)

In [6]:
columns = movie.columns
columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='str')

In [7]:
data = movie.values
data

array([['Color', 'James Cameron', 723.0, ..., 7.9, 1.78, 33000],
       ['Color', 'Gore Verbinski', 302.0, ..., 7.1, 2.35, 0],
       ['Color', 'Sam Mendes', 602.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Color', 'Benjamin Roberds', 13.0, ..., 6.3, nan, 16],
       ['Color', 'Daniel Hsia', 14.0, ..., 6.3, 2.35, 660],
       ['Color', 'Jon Gunn', 43.0, ..., 6.6, 1.85, 456]],
      shape=(4916, 28), dtype=object)

In [8]:
type(index)

pandas.RangeIndex

In [9]:
type(columns)

pandas.Index

In [10]:
type(data)

numpy.ndarray

In [11]:
issubclass(pd.RangeIndex, pd.Index)

True

In [12]:
index.values

array([   0,    1,    2, ..., 4913, 4914, 4915], shape=(4916,))

In [13]:
columns.values

<StringArray>
[                    'color',             'director_name',
    'num_critic_for_reviews',                  'duration',
   'director_facebook_likes',    'actor_3_facebook_likes',
              'actor_2_name',    'actor_1_facebook_likes',
                     'gross',                    'genres',
              'actor_1_name',               'movie_title',
           'num_voted_users', 'cast_total_facebook_likes',
              'actor_3_name',      'facenumber_in_poster',
             'plot_keywords',           'movie_imdb_link',
      'num_user_for_reviews',                  'language',
                   'country',            'content_rating',
                    'budget',                'title_year',
    'actor_2_facebook_likes',                'imdb_score',
              'aspect_ratio',      'movie_facebook_likes']
Length: 28, dtype: str

<center>
    <h2>Data types</h2>
</center>
<table>
    <tr>
        <b>
        <th>Common data type name</th>
        <th>NumPy/pandas object</th>
        <th>Pandas string name</th>
        <th>Notes</th>
        </b>
    </tr>
    <tr>
        <td><b>Boolean</b></td>
        <td>np.bool</td>
        <td><i>bool</i></td>
        <td>Stored as a single byte</td>
    </tr>
    <tr>
        <td><b>Integer</b></td>
        <td>np.int</td>
        <td><i>int</i></td>
        <td>Defalted to 64 bits. Unsigned ints are also availible - np.uint</td>
    </tr>
    <tr>
        <td><b>Float</b></td>
        <td>np.float</td>
        <td><i>float</i></td>
        <td>DEfaulted to 64 bits</td>
    </tr>
    <tr>
        <td><b>Complex</b></td>
        <td>np.complex</td>
        <td><i>complex</i></td>
        <td>Rarely seen in data analysis</td>
    </tr>
    <tr>
        <td><b>Object</b></td>
        <td>np.object</td>
        <td><i>O, object</i></td>
        <td>Typically string but is a catchall for columns with multiple different types or other Pythn objects (tuples, lists, dicts, and so on)</td>
    </tr>
    <tr>
        <td><b>Datetime</b></td>
        <td><p>np.datetime64,</p><p>pd.Timestamp</p></td>
        <td><i>datetime64</i></td>
        <td>Specific moment in time with nanosecond precision</td>
    </tr>
    <tr>
        <td><b>Timedelta</b></td>
        <td><p>np.timedelta64</p><p>pd.Timedelta</p></td>
        <td><i>timedelta64</i></td>
        <td>An amount of time, from dats to nanoseconds</td>
    </tr>
    <tr>
        <td><b>Catgorical</b></td>
        <td>pd.Categorical</td>
        <td><i>category</i></td>
        <td>Specific only to pandas. Useful for object columns with relatively few unique values</td>
    </tr>
        

</table>

<h4>We can use <i>dtypes</i> attribute to display each column along with its data type</h4>

In [14]:
movie.dtypes

color                            str
director_name                    str
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                     str
actor_1_facebook_likes       float64
gross                        float64
genres                           str
actor_1_name                     str
movie_title                      str
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                     str
facenumber_in_poster         float64
plot_keywords                    str
movie_imdb_link                  str
num_user_for_reviews         float64
language                         str
country                          str
content_rating                   str
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

<h4>We can use <i>get_dtype_counts</i> method to return the counts of each data type:</h4>
<p><i>get_dtype_counts</i> desapareció de Python, pero usaremos la alternativa equivalente  de <i>value_counts()</i></p>

In [15]:
movie.dtypes.value_counts()

float64    13
str        12
int64       3
Name: count, dtype: int64

<h2>Selecting a single column of data as a Series</h2>
<i>This recipe examines two different syntaxies</i>

In [16]:
movie["director_name"]

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: str

In [17]:
movie.director_name

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: str

In [18]:
type(movie["director_name"])

pandas.Series

<h4>How to turn series into coumn DataFrame with <i>to_frame</i> method</h4>

In [19]:
director = movie["director_name"]
director

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: str

In [20]:
type(movie["director_name"])

pandas.Series

In [21]:
director.to_frame()

          director_name
0         James Cameron
1        Gore Verbinski
2            Sam Mendes
3     Christopher Nolan
4           Doug Walker
...                 ...
4911        Scott Smith
4912                NaN
4913   Benjamin Roberds
4914        Daniel Hsia
4915           Jon Gunn

[4916 rows x 1 columns]

In [22]:
type(director)

pandas.Series

<h4>We can use the <i>dir</i> function to uncoverall the attributes and methods of a Series We can find the number of attributies and methods common to both sries and DataFrames</h4>

In [23]:
s_attr_methods = set(dir(pd.Series))
len(s_attr_methods)

394

In [24]:
df_attr_methods = set(dir(pd.DataFrame))
len(df_attr_methods)

415

In [25]:
len(s_attr_methods & df_attr_methods)

346

<p><b>After reading te dataset, let's create two series with diferent data type </b></p>

<p><i>director_name</i> contain strings</p>

In [26]:
director = movie["director_name"]
director.head()

0        James Cameron
1       Gore Verbinski
2           Sam Mendes
3    Christopher Nolan
4          Doug Walker
Name: director_name, dtype: str

<p><i>actor_1_fb_likes</i> contain numerical data</p>

In [27]:
actor_1_fb_likes = movie["actor_1_facebook_likes"]

In [28]:
actor_1_fb_likes.head()

0     1000.0
1    40000.0
2    11000.0
3    27000.0
4      131.0
Name: actor_1_facebook_likes, dtype: float64

<b>One of the most useful methods for the object data type series is <i>value_counts()</i>. wich counts all the occurrences of wach unique value:</b>

In [29]:
director.value_counts()

director_name
Steven Spielberg    26
Woody Allen         22
Martin Scorsese     20
Clint Eastwood      20
Ridley Scott        16
                    ..
Neill Dela Llana     1
Anthony Vallone      1
Scott Smith          1
Benjamin Roberds     1
Daniel Hsia          1
Name: count, Length: 2397, dtype: int64

<b><i>value_counts()</i> is typically more useful with object data, but occasionally provide insight into numeric Series as well</b>

In [30]:
actor_1_fb_likes.value_counts()

actor_1_facebook_likes
1000.0     436
11000.0    206
2000.0     189
3000.0     150
12000.0    131
          ...
313.0        1
370.0        1
630.0        1
10.0         1
291.0        1
Name: count, Length: 877, dtype: int64

<b>Counting the number of elements in the Series with:</b>
<ul>
    <li><i>size</i></li>
    <li><i>shape</i></li>
    <li><i>len()</i></li>
</ul>

In [31]:
director.size

4916

In [32]:
director.shape

(4916,)

In [33]:
len(director)

4916

<b><i>Count()</i> method return the number of non-missing values:</b>

In [34]:
director.count()

np.int64(4814)

In [35]:
actor_1_fb_likes.count()

np.int64(4909)

<b>Basic summary statistics:</b>
<ul>
    <li><i>min</i></li>
    <li><i>max</li>
    <li><i>mean</li>
    <li><i>median</i></li>
    <li><i>std</i></li>
    <li><i>sum</i></li>
</ul>
<h4>Movies statistics summary's</h4>

In [36]:
print("The minimun value  is: ", actor_1_fb_likes.min())
print("The maximun value is: ", actor_1_fb_likes.max())
print("The mean value is: ", actor_1_fb_likes.mean())
print("The median value is: ", actor_1_fb_likes.median())
print("The 'std' value is: ", actor_1_fb_likes.std())
print("The sum of the values is: ", actor_1_fb_likes.sum())

The minimun value  is:  0.0
The maximun value is:  640000.0
The mean value is:  6494.488490527602
The median value is:  982.0
The 'std' value is:  15106.986883848185
The sum of the values is:  31881444.0

<b>We can simplify that with <i>describe()</i> method to return the summary statistics</b>

In [37]:
actor_1_fb_likes.describe()

count      4909.000000
mean       6494.488491
std       15106.986884
min           0.000000
25%         607.000000
50%         982.000000
75%       11000.000000
max      640000.000000
Name: actor_1_facebook_likes, dtype: float64

In [38]:
director.describe()

count                 4814
unique                2397
top       Steven Spielberg
freq                    26
Name: director_name, dtype: object

<b>The <i>quantile()</i> method ecists to calculate an exact quantile of numeric data:</b>

In [39]:
actor_1_fb_likes.quantile(0.2)

np.float64(510.0)

In [40]:
actor_1_fb_likes.quantile([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

0.1      240.0
0.2      510.0
0.3      694.0
0.4      854.0
0.5      982.0
0.6     1000.0
0.7     8000.0
0.8    13000.0
0.9    18000.0
Name: actor_1_facebook_likes, dtype: float64

<b>The <i>isnull()</i> method may be used to determine wheter wach individual value is missign or not<b>

In [41]:
director.isnull()

0       False
1       False
2       False
3       False
4       False
        ...
4911    False
4912     True
4913    False
4914    False
4915    False
Name: director_name, Length: 4916, dtype: bool

<p><b>There exist a complement of <i>is null</i>: the <i>notnull</i></b></p>

In [42]:
director.notnull()

0        True
1        True
2        True
3        True
4        True
        ...
4911     True
4912    False
4913     True
4914     True
4915     True
Name: director_name, Length: 4916, dtype: bool

<b>It's posible to repalce all missing values within a Series with the <i>fillna()</i> method</b>

In [43]:
actor_1_fb_likes_filled = actor_1_fb_likes.fillna(0)
actor_1_fb_likes_filled.count()

np.int64(4916)

<b>To remove the Series elements with missign values, use <i>dropna()</i> method</b>

In [44]:
actor_1_fb_likes_dropped = actor_1_fb_likes.dropna()
actor_1_fb_likes_dropped.size

4909

<h4>(normalize = True)</h4>
<p><i>Return the normalized values</i></p>

In [45]:
director.value_counts(normalize=True)

director_name
Steven Spielberg    0.005401
Woody Allen         0.004570
Martin Scorsese     0.004155
Clint Eastwood      0.004155
Ridley Scott        0.003324
                      ...
Neill Dela Llana    0.000208
Anthony Vallone     0.000208
Scott Smith         0.000208
Benjamin Roberds    0.000208
Daniel Hsia         0.000208
Name: proportion, Length: 2397, dtype: float64

<h2>Operators</h2>

In [46]:
imdb_score = movie["imdb_score"]
imdb_score

0       7.9
1       7.1
2       6.8
3       8.5
4       7.1
       ...
4911    7.7
4912    7.5
4913    6.3
4914    6.3
4915    6.6
Name: imdb_score, Length: 4916, dtype: float64

<h4>Plus operator</h4>

In [47]:
imdb_score + 1

0       8.9
1       8.1
2       7.8
3       9.5
4       8.1
       ...
4911    8.7
4912    8.5
4913    7.3
4914    7.3
4915    7.6
Name: imdb_score, Length: 4916, dtype: float64

<h4>Multiply operator</h4>

In [48]:
imdb_score * 2.5

0       19.75
1       17.75
2       17.00
3       21.25
4       17.75
        ...
4911    19.25
4912    18.75
4913    15.75
4914    15.75
4915    16.50
Name: imdb_score, Length: 4916, dtype: float64

<h4>Floor division operator</h4>

In [49]:
imdb_score // 7

0       1.0
1       1.0
2       0.0
3       1.0
4       1.0
       ...
4911    1.0
4912    1.0
4913    0.0
4914    0.0
4915    0.0
Name: imdb_score, Length: 4916, dtype: float64

<h4>Comparison operators</h4>

In [50]:
imdb_score > 7

0        True
1        True
2       False
3        True
4        True
        ...
4911     True
4912     True
4913    False
4914    False
4915    False
Name: imdb_score, Length: 4916, dtype: bool

<h4>All the operators have method equivalents that produce the exact same result</h4>

<center>
    <h3><b>Operators</b></h3>
</center>

<table>
    <tr>
        <th><b>Operator Group</b></th>
        <th><b>Operator</b></th>
        <th><b>series method</b></th>
    </tr>
    <tr>
        <td>Arithmetic</td>
        <td>+, -, *, /, //, %, **</td>
        <td>add, sub, mul, div, floordiv, mod, pow</td>
    </tr>
    <tr>
        <td>Comparison</td>
        <td><, >, <=, >=, ==, !=</td>
        <td>lt, gt, le, ge, eq, ne</td>
    </tr>
        
</table>

<h4><i>Example</i></h4>

<table>
    <tr>
        <th><b>Method</b></th>
        <th><b>Operator</b></th>
    </tr>
    <tr>
        <td>imbd_score.add(1)</td>
        <td>imdb_score + 1</td>
    </tr>
    <tr>
        <td>imdb_score.mul(2.5)</td>
        <td>imdb_score * 2.5</td>
    </tr>
    <tr>
        <td>imdb_score.floordiv(7)</td>
        <td>imbd_score // 7</td>
    </tr>
    <tr>
        <td>imdb_score.gt(7)</td>
        <td>imdb_score > 7</td>
    </tr>
    <tr>
        <td>director.eq("James Cameron")</td>
        <td>director == "James cameron"</td>
    </tr>
</table>

<center>
    <h3>Chaining method</h3>
</center>

<center>
<i>One of the mos common method to append to the chain, is the <b>head</b> method. This suppresses long output. For shorter chains, there isn't as great a need to place each method on a different line</i>
</center>

In [51]:
director.value_counts().head(3)

director_name
Steven Spielberg    26
Woody Allen         22
Martin Scorsese     20
Name: count, dtype: int64

<i>To count the number of missing values is to chain the sum method after isnull</i>

In [52]:
actor_1_fb_likes.isnull().sum()

np.int64(7)

In [53]:
actor_1_fb_likes.dtype

dtype('float64')

In [54]:
actor_1_fb_likes.fillna(0).astype(int).head()

0     1000
1    40000
2    11000
3    27000
4      131
Name: actor_1_facebook_likes, dtype: int64

<i>Porcentage of values that are missing:</i>

In [55]:
actor_1_fb_likes.isnull().mean()

np.float64(0.0014239218877135883)

<center><h2>Rename Rows and Columns</h2></center>

<center>
<i>The <b>rename</b> DataFrame method accepts dictionaries that map the old value to the new value.</i>
</center>

In [56]:
movie = movie.set_index("movie_title")

In [57]:
idx_rename = {"Avatar":"Ratava", "Spectre":"Ertceps"} 
col_rename = {"director_name":"Director name", "num_critic_for_reviews":"Critical Reviews"}

In [58]:
movie_renamed = movie.rename(index=idx_rename, columns=col_rename)
movie_renamed

,color,Director name,Critical Reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
Ratava,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Ertceps,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Signed Sealed Delivered,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
The Following,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
A Plague So Pleasant,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
Shanghai Calling,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
My Date with Drew,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

<center>
<i>Others methods to rename</i>
</center>

In [59]:
index = movie.index
columns = movie.columns

index_list = index.tolist()
column_list = columns.tolist()

#Rename the row and column labels with list assigments
index_list[0] = "Ratava"
index_list[1] = "Ertceps"
column_list[1] = "Director Name"
column_list[2] = "Critical Reviews"

movie.index = index_list
movie.columns = column_list

movie.head()

,color,Director Name,Critical Reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
Ratava,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Ertceps,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

<center>
    <h2>Creating and deleting columns</h2>
</center>

<i>Let's create a new column "has seen"</i>

In [60]:
movie["has_seen"] = 0

In [61]:
movie["has_seen"].head()

Ratava                                        0
Ertceps                                       0
Spectre                                       0
The Dark Knight Rises                         0
Star Wars: Episode VII - The Force Awakens    0
Name: has_seen, dtype: int64

<i>There are several columns that contain data on the number of Facebook likes. Let's define a column with the name "actor_director_facebook_likes"</i>

In [62]:
movie["actor_director_facebook_likes"] = \
(movie["actor_1_facebook_likes"] + 
 movie["actor_2_facebook_likes"] + 
 movie["actor_3_facebook_likes"] + 
 movie["director_facebook_likes"])

In [63]:
movie["actor_director_facebook_likes"].isnull().sum()

np.int64(122)

In [64]:
movie["actor_director_facebook_likes"] = \
movie["actor_director_facebook_likes"].fillna(0)

<center>
    <h4>Exercise<h4> 
</center>

<center><i>There's another column in the dataset named cast_total_facebook_likes. IOt would be interesnting to see what porcentage os this column comes from our newly created column, actor_director_facebook_likes. Before we create our porcentage column, let's do some basic data validation. Let's ensure that cast_total_facebook_likes is greater that or equal to ctor_director_facebook_likes</i></center>

In [65]:
movie["is_cast_likes_more"] = \
(movie["cast_total_facebook_likes"] >=
 movie["actor_director_facebook_likes"])

<center>
    <i>is_cast_like_more is now a column of boolean values. We can check whether all the values of this column are True with all Series methos</i>
</center>

In [66]:
movie["is_cast_likes_more"].all()

np.False_

<center><i>It turns out that there is at least one movie with more actor_director_facebook_likes than cast_total_facebook_likes. It could be that director Facebook likes are not part of the cast total likes. Let's backtrack and delet column actor_director_facebook_likes</i></center>

In [67]:
movie = movie.drop("actor_director_facebook_likes",axis="columns")

<center>
    <i>Let's recreate a column of just the total actor likes</i>
</center>

In [68]:
movie["actor_total_facebook_likes"] = \
(movie["actor_1_facebook_likes"] +
 movie["actor_2_facebook_likes"] + 
 movie["actor_3_facebook_likes"])

In [69]:
movie["actor_total_facebook_likes"] = \
movie["actor_total_facebook_likes"].fillna(0)

<center>
    <i>Chekc again whether all the values in cast_total_facebook_likes are greater than the actor_total_facebook_likes:</i>
</center>

In [70]:
movie["is_cast_likes_more"] = \
(movie["cast_total_facebook_likes"] >=
 movie["actor_total_facebook_likes"])

movie["is_cast_likes_more"].all()

np.True_

<center>
    <i>Finally, let's calculate the porcentage of the cast_total_facebook_likes that come fron actor_total_facebook_likes: </i>
</center>

In [71]:
movie["pct_actor_cast_like"] = \
(movie["actor_total_facebook_likes"] /
 movie["cast_total_facebook_likes"])

<center>
    <i>Let's validate that the min and max of this column- fall between 0 and 1</i>
</center>

In [72]:
(movie["pct_actor_cast_like"].min(), movie["pct_actor_cast_like"].max())

(np.float64(0.0), np.float64(1.0))

<center>
    <i>We can output this column as a Series. First, we need so set the index to the movie title so we can properly indentify each value</i>
</center>

In [73]:
movie["pct_actor_cast_like"].head()

Ratava                                        0.577369
Ertceps                                       0.951396
Spectre                                       0.987521
The Dark Knight Rises                         0.683783
Star Wars: Episode VII - The Force Awakens    0.000000
Name: pct_actor_cast_like, dtype: float64

<center>
<b><i>And anternative method to delete columns is to use the del statement</i></b>
</center>

In [74]:
# del movie["actor_director_faceboob_likes"]

<center>
    <h1>
        <b>2. Essential DataFrame Operations</b>
    </h1>
</center>

<center>
<h3><b>Selecting multiple DataFrame columns</b></h3>
</center>

In [75]:
movie_actor_director = movie[["actor_1_name", "actor_2_name", "actor_3_name", "Director Name"]]
movie_actor_director

,actor_1_name,actor_2_name,actor_3_name,Director Name
Ratava,CCH Pounder,Joel David Moore,Wes Studi,James Cameron
Ertceps,Johnny Depp,Orlando Bloom,Jack Davenport,Gore Verbinski
Spectre,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Sam Mendes
The Dark Knight Rises,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Christopher Nolan
Star Wars: Episode VII - The Force Awakens,Doug Walker,Rob Walker,NaN,Doug Walker
...,...,...,...,...
Signed Sealed Delivered,Eric Mabius,Daphne Zuniga,Crystal Lowe,Scott Smith
The Following,Natalie Zea,Valorie Curry,Sam Underwood,NaN
A Plague So Pleasant,Eva Boehnke,Maxwell Moody,David Chandler,Benjamin Roberds
Shanghai Calling,Alan Ruck,Daniel Henney,Eliza Coupe,Daniel Hsia
My Date with Drew,John August,Brian Herzlinger,Jon Gunn,Jon Gunn

<center>
    <i>We can reset the value of the set_index to the default, and return "movie title" like a column for default using the rese_index() method</i>
</center>

In [76]:
movie = movie.reset_index()
movie.head()

,index,color,Director Name,Critical Reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,...,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,is_cast_likes_more,actor_total_facebook_likes,pct_actor_cast_like
0,Ratava,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,...,237000000.0,2009.0,936.0,7.9,1.78,33000,0,True,2791.0,0.577369
1,Ertceps,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,...,300000000.0,2007.0,5000.0,7.1,2.35,0,0,True,46000.0,0.951396
2,Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,...,245000000.0,2015.0,393.0,6.8,2.35,85000,0,True,11554.0,0.987521
3,The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,...,250000000.0,2012.0,23000.0,8.5,2.35,164000,0,True,73000.0,0.683783
4,Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,...,NaN,NaN,12.0,7.1,NaN,0,0,True,0.0,0.000000

<center>
    <i>We can select just one element of the DataFrame</i>
</center>

In [77]:
movie[["Director Name"]].head()

       Director Name
0      James Cameron
1     Gore Verbinski
2         Sam Mendes
3  Christopher Nolan
4        Doug Walker

<center>
    <i>We can define the columns on a variable</i>
</center>

In [78]:
col = ["actor_1_name", "actor_2_name", "actor_3_name", "Director Name"]
movie_actor_director = movie[col]

In [79]:
movie_actor_director.head()

      actor_1_name      actor_2_name          actor_3_name      Director Name
0      CCH Pounder  Joel David Moore             Wes Studi      James Cameron
1      Johnny Depp     Orlando Bloom        Jack Davenport     Gore Verbinski
2  Christoph Waltz      Rory Kinnear      Stephanie Sigman         Sam Mendes
3        Tom Hardy    Christian Bale  Joseph Gordon-Levitt  Christopher Nolan
4      Doug Walker        Rob Walker                   NaN        Doug Walker

<center>
    <h3><b>Selecting columns with methods</b></h3>
</center>

<center>
    <i>Return the number of columns with each specific data type:</i>

</center>

In [80]:
movie.dtypes.value_counts()

float64    15
str        12
int64       4
bool        1
Name: count, dtype: int64

<center>
    <i>Use the select_dtypes method to select just tje integer columns</i>
</center>

In [81]:
movie.select_dtypes(include=["int"]).head()

   num_voted_users  cast_total_facebook_likes  movie_facebook_likes  has_seen
0           886204                       4834                 33000         0
1           471220                      48350                     0         0
2           275868                      11700                 85000         0
3          1144337                     106759                164000         0
4                8                        143                     0         0

<center>
    <i>If you want to select all the numeric columns, you've to pass string "number"  to the include parameter</i>
</center>

In [82]:
movie.select_dtypes(include=["number"]).head()

,Critical Reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,actor_total_facebook_likes,pct_actor_cast_like
0,723.0,178.0,0.0,855.0,1000.0,760505847.0,886204,4834,0.0,3054.0,237000000.0,2009.0,936.0,7.9,1.78,33000,0,2791.0,0.577369
1,302.0,169.0,563.0,1000.0,40000.0,309404152.0,471220,48350,0.0,1238.0,300000000.0,2007.0,5000.0,7.1,2.35,0,0,46000.0,0.951396
2,602.0,148.0,0.0,161.0,11000.0,200074175.0,275868,11700,1.0,994.0,245000000.0,2015.0,393.0,6.8,2.35,85000,0,11554.0,0.987521
3,813.0,164.0,22000.0,23000.0,27000.0,448130642.0,1144337,106759,0.0,2701.0,250000000.0,2012.0,23000.0,8.5,2.35,164000,0,73000.0,0.683783
4,NaN,NaN,131.0,NaN,131.0,NaN,8,143,0.0,NaN,NaN,NaN,12.0,7.1,NaN,0,0,0.0,0.000000

<center>
    <i>An altenrative method to select columns is with the like() method. This method is flexible and searches column names based on which parametr is used</i>
</center>

In [83]:
movie.filter(like="facebook").head()

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes,actor_total_facebook_likes
0,0.0,855.0,1000.0,4834,936.0,33000,2791.0
1,563.0,1000.0,40000.0,48350,5000.0,0,46000.0
2,0.0,161.0,11000.0,11700,393.0,85000,11554.0
3,22000.0,23000.0,27000.0,106759,23000.0,164000,73000.0
4,131.0,NaN,131.0,143,12.0,0,0.0

<center>
    <i>The filter metjod allows columns to tbe searched trhough regular expressions with the regex parameter. Here, we search for all columns that have a digit somewhere iin their name</i>
</center>

In [84]:
movie.filter(regex=r"\d").head()

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
0,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
1,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
2,161.0,Rory Kinnear,11000.0,Christoph Waltz,Stephanie Sigman,393.0
3,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
4,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0

<center>
    <h3><b>Ordering column names sensibility</b></h3>
</center>

In [85]:
movie.head()

,index,color,Director Name,Critical Reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,...,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,is_cast_likes_more,actor_total_facebook_likes,pct_actor_cast_like
0,Ratava,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,...,237000000.0,2009.0,936.0,7.9,1.78,33000,0,True,2791.0,0.577369
1,Ertceps,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,...,300000000.0,2007.0,5000.0,7.1,2.35,0,0,True,46000.0,0.951396
2,Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,...,245000000.0,2015.0,393.0,6.8,2.35,85000,0,True,11554.0,0.987521
3,The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,...,250000000.0,2012.0,23000.0,8.5,2.35,164000,0,True,73000.0,0.683783
4,Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,...,NaN,NaN,12.0,7.1,NaN,0,0,True,0.0,0.000000

<center>
    <i>output the column names</i>
</center>

In [86]:
movie.columns

Index(['index', 'color', 'Director Name', 'Critical Reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'num_voted_users', 'cast_total_facebook_likes', 'actor_3_name',
       'facenumber_in_poster', 'plot_keywords', 'movie_imdb_link',
       'num_user_for_reviews', 'language', 'country', 'content_rating',
       'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score',
       'aspect_ratio', 'movie_facebook_likes', 'has_seen',
       'is_cast_likes_more', 'actor_total_facebook_likes',
       'pct_actor_cast_like'],
      dtype='str')

In [87]:
try:
    movie = movie.drop("level_0", axis="columns") 
except KeyError:
    print("La columna 'level_0' no existe, así que no se eliminó.")

La columna 'level_0' no existe, así que no se eliminó.

In [88]:
movie.head(1)

,index,color,Director Name,Critical Reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,...,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,is_cast_likes_more,actor_total_facebook_likes,pct_actor_cast_like
0,Ratava,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,...,237000000.0,2009.0,936.0,7.9,1.78,33000,0,True,2791.0,0.577369

In [89]:
movie = movie.rename(columns={"movie name":"movie_title"})
movie.head(1)

,index,color,Director Name,Critical Reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,...,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,is_cast_likes_more,actor_total_facebook_likes,pct_actor_cast_like
0,Ratava,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,...,237000000.0,2009.0,936.0,7.9,1.78,33000,0,True,2791.0,0.577369

<i>The columns don't have any logical ordering to them</i>

In [90]:
movie.columns

Index(['index', 'color', 'Director Name', 'Critical Reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'num_voted_users', 'cast_total_facebook_likes', 'actor_3_name',
       'facenumber_in_poster', 'plot_keywords', 'movie_imdb_link',
       'num_user_for_reviews', 'language', 'country', 'content_rating',
       'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score',
       'aspect_ratio', 'movie_facebook_likes', 'has_seen',
       'is_cast_likes_more', 'actor_total_facebook_likes',
       'pct_actor_cast_like'],
      dtype='str')

In [91]:
disc_core = ["index", "title_year", "content_rating", "genres"]

disc_people = ["Director Name", "actor_1_name", "actor_2_name", "actor_3_name"] 

disc_other = ["color", "country", "language", "plot_keywords", "movie_imdb_link"]

cont_fb = ["director_facebook_likes", "actor_1_facebook_likes", "actor_2_facebook_likes", "actor_3_facebook_likes", "cast_total_facebook_likes", \
            "movie_facebook_likes"]

cont_finance = ["budget", "gross"]

cont_num_reviews = ["num_voted_users", "num_user_for_reviews", "Critical Reviews"]

cont_other = ["imdb_score", "duration", "aspect_ratio", "facenumber_in_poster"]

<center>
    <i>Concatenate all the lists together to get the final column order</i>
</center>

In [92]:
new_col_order = (disc_core +
                 disc_people +
                 disc_other +
                 cont_fb +
                 cont_finance +
                 cont_num_reviews +
                 cont_other)

set(movie.columns) == set(new_col_order)

False

<center>
    <i>The last function returns "False", we have to know witch don't match</i>
</center>

In [93]:
dont_match = set(movie.columns) - set(new_col_order)
dont_match

{'actor_total_facebook_likes',
 'has_seen',
 'is_cast_likes_more',
 'pct_actor_cast_like'}

<center>
    <i>This columns are the columns that we create before to make some measures </i>
</center>

In [94]:
movie2 = movie[new_col_order]
movie2.head()

,index,title_year,content_rating,genres,Director Name,actor_1_name,actor_2_name,actor_3_name,color,country,...,movie_facebook_likes,budget,gross,num_voted_users,num_user_for_reviews,Critical Reviews,imdb_score,duration,aspect_ratio,facenumber_in_poster
0,Ratava,2009.0,PG-13,Action|Adventure|Fantasy|Sci-Fi,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Color,USA,...,33000,237000000.0,760505847.0,886204,3054.0,723.0,7.9,178.0,1.78,0.0
1,Ertceps,2007.0,PG-13,Action|Adventure|Fantasy,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Color,USA,...,0,300000000.0,309404152.0,471220,1238.0,302.0,7.1,169.0,2.35,0.0
2,Spectre,2015.0,PG-13,Action|Adventure|Thriller,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Color,UK,...,85000,245000000.0,200074175.0,275868,994.0,602.0,6.8,148.0,2.35,1.0
3,The Dark Knight Rises,2012.0,PG-13,Action|Thriller,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Color,USA,...,164000,250000000.0,448130642.0,1144337,2701.0,813.0,8.5,164.0,2.35,0.0
4,Star Wars: Episode VII - The Force Awakens,NaN,NaN,Documentary,Doug Walker,Doug Walker,Rob Walker,NaN,NaN,NaN,...,0,NaN,NaN,8,NaN,NaN,7.1,NaN,NaN,0.0

<center>
    <i>Pass the list with the new column order to the indexing operator of the DataFrame to reorder the columns:</i>
</center>

<center>
    <h3><b>Operating on the entire DataFrame</b></h3>
</center>

<p><b>Read in the movie dataset, and grab the basic descriptive attributes, <i>shape</i>, <i>size</i> and <i>ndim</i>, along with the <i>len</i> function</b></p>

In [95]:
movie.shape

(4916, 32)

In [96]:
movie.size

157312

In [97]:
movie.ndim

2

In [98]:
len(movie)

4916

<p><b>Use the <i>count</i> method to find the number of non-missing values for each column. The output is a Series that now has the old column names as its index:</b></p>

In [99]:
movie.count()

index                         4916
color                         4897
Director Name                 4814
Critical Reviews              4867
duration                      4901
director_facebook_likes       4814
actor_3_facebook_likes        4893
actor_2_name                  4903
actor_1_facebook_likes        4909
gross                         4054
genres                        4916
actor_1_name                  4909
num_voted_users               4916
cast_total_facebook_likes     4916
actor_3_name                  4893
facenumber_in_poster          4903
plot_keywords                 4764
movie_imdb_link               4916
num_user_for_reviews          4895
language                      4902
country                       4911
content_rating                4616
budget                        4432
title_year                    4810
actor_2_facebook_likes        4903
imdb_score                    4916
aspect_ratio                  4590
movie_facebook_likes          4916
has_seen                      4916
is_cast_likes_more            4916
actor_total_facebook_likes    4916
pct_actor_cast_like           4883
dtype: int64

<p><b>The other methods that compute summary statistics such as <i>min, max, mean, median</i> and <i>std</i> all return similar series, with column names in the index and their computational result as the values</b></p>

In [100]:
movie.min()

index                                                                   #Horror
color                                                           Black and White
Director Name                                                     A. Raven Cruz
Critical Reviews                                                            1.0
duration                                                                    7.0
director_facebook_likes                                                     0.0
actor_3_facebook_likes                                                      0.0
actor_2_name                                                            50 Cent
actor_1_facebook_likes                                                      0.0
gross                                                                     162.0
genres                                                                   Action
actor_1_name                                                            50 Cent
num_voted_users                                                               5
cast_total_facebook_likes                                                     0
actor_3_name                                                            50 Cent
facenumber_in_poster                                                        0.0
plot_keywords                          10 year old|dog|florida|girl|supermarket
movie_imdb_link               http://www.imdb.com/title/tt0006864/?ref_=fn_t...
num_user_for_reviews                                                        1.0
language                                                             Aboriginal
country                                                             Afghanistan
content_rating                                                         Approved
budget                                                                    218.0
title_year                                                               1916.0
actor_2_facebook_likes                                                      0.0
imdb_score                                                                  1.6
aspect_ratio                                                               1.18
movie_facebook_likes                                                          0
has_seen                                                                      0
is_cast_likes_more                                                         True
actor_total_facebook_likes                                                  0.0
pct_actor_cast_like                                                         0.0
dtype: object

In [101]:
movie.max()

index                                                                  Æon Flux
color                                                                     Color
Director Name                                                     Étienne Faure
Critical Reviews                                                          813.0
duration                                                                  511.0
director_facebook_likes                                                 23000.0
actor_3_facebook_likes                                                  23000.0
actor_2_name                                                      Zubaida Sahar
actor_1_facebook_likes                                                 640000.0
gross                                                               760505847.0
genres                                                                  Western
actor_1_name                                                      Óscar Jaenada
num_voted_users                                                         1689764
cast_total_facebook_likes                                                656730
actor_3_name                                                      Óscar Jaenada
facenumber_in_poster                                                       43.0
plot_keywords                                               zombie|zombie spoof
movie_imdb_link               http://www.imdb.com/title/tt5574490/?ref_=fn_t...
num_user_for_reviews                                                     5060.0
language                                                                   Zulu
country                                                            West Germany
content_rating                                                                X
budget                                                             4200000000.0
title_year                                                               2016.0
actor_2_facebook_likes                                                 137000.0
imdb_score                                                                  9.5
aspect_ratio                                                               16.0
movie_facebook_likes                                                     349000
has_seen                                                                      0
is_cast_likes_more                                                         True
actor_total_facebook_likes                                             655000.0
pct_actor_cast_like                                                         1.0
dtype: object

<p><b>The <i>describe</i> method is very powerfull and calculates all the descriptive statistics and quartiles in the preceding steps all at once. The end result is a DataFrame ith the descriptive statistics as its index</b></p>

In [102]:
movie.describe()

,Critical Reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,actor_total_facebook_likes,pct_actor_cast_like
count,4867.000000,4901.000000,4814.000000,4893.000000,4909.000000,4.054000e+03,4.916000e+03,4916.000000,4903.000000,4895.000000,4.432000e+03,4810.000000,4903.000000,4916.000000,4590.000000,4916.000000,4916.0,4916.000000,4883.000000
mean,137.988905,107.090798,691.014541,631.276313,6494.488491,4.764451e+07,8.264492e+04,9579.815907,1.377320,267.668846,3.654749e+07,2002.447609,1621.923516,6.437429,2.222349,7348.294142,0.0,8728.037225,0.830821
std,120.239379,25.286015,2832.954125,1625.874802,15106.986884,6.737255e+07,1.383222e+05,18164.316990,2.023826,372.934839,1.002427e+08,12.453977,4011.299523,1.127802,1.402940,19206.016458,0.0,17682.483804,0.146257
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000,0.0,0.000000,0.000000
25%,49.000000,93.000000,7.000000,132.000000,607.000000,5.019656e+06,8.361750e+03,1394.750000,0.000000,64.000000,6.000000e+06,1999.000000,277.000000,5.800000,1.850000,0.000000,0.0,1122.750000,0.733884
50%,108.000000,103.000000,48.000000,366.000000,982.000000,2.504396e+07,3.313250e+04,3049.000000,1.000000,153.000000,1.985000e+07,2005.000000,593.000000,6.600000,2.350000,159.000000,0.0,2145.500000,0.868432
75%,191.000000,118.000000,189.750000,633.000000,11000.000000,6.110841e+07,9.377275e+04,13616.750000,2.000000,320.500000,4.300000e+07,2011.000000,912.000000,7.200000,2.350000,2000.000000,0.0,12651.000000,0.954126
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,4.200000e+09,2016.000000,137000.000000,9.500000,16.000000,349000.000000,0.0,655000.000000,1.000000

<center>
    <h3><b>Chaining DataFrame</b></h3<
</center>

<p>To get a count of the missing values, the <i>null</i> method must first be called to change each DataFrame value to a boolean. Let's call this method on the movie dataset:</p>

In [103]:
movie.isnull().head()

,index,color,Director Name,Critical Reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,...,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,is_cast_likes_more,actor_total_facebook_likes,pct_actor_cast_like
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,True,False,True,True,False,True,False,False,True,...,True,True,False,False,True,False,False,False,False,False

<p><b>We will chain the <i>sum</i> method that interptrests <i>True/False</i> booleans as 1/0. Notice that a Series is returned</p>

In [104]:
movie.isnull().sum().head()

index                 0
color                19
Director Name       102
Critical Reviews     49
duration             15
dtype: int64

<p><b>We can go one step further and take the sum of this Series and return the count of the total number of missing values in the entire DataFrame as a scalar value:</b></p>

In [105]:
movie.isnull().sum().sum()

np.int64(2689)

<p><b>A slight deviation is to determine whether there are any missing values in the DataFrame. We use the <i>any</i> method here </p>

In [106]:
movie.isnull().any().any()

np.True_

<center>
    <h3><b>Working with operators on a DataFrame</b></h3>
</center>

<i>If the DataFrame does'nt contain homogeneous data, then the operation is likely to fail. Let's see an example</i>

<h3><b>DataFrame [College]</b></h3>

In [107]:
url1 = r"C:\Users\uih30853\OneDrive - Aumovio SE\Desktop\college.csv"

In [108]:
college = pd.read_csv(url1)
college.head()

,INSTNM,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
0,Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
1,University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
2,Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
3,University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
4,Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5

In [109]:
try: 
    college + 5
except TypeError as e: 
    print(e)

can only concatenate str (not "int") to str

<p><b>To successfully use an operator with a DataFrame, first select homogeneous data. First we will select all the columns that begin with <i>UGDS_</i>. To get started, we import the data and use the institution name as the label for our index, the select the columns we desire with the <i>filter</i> method</b></p>

In [110]:
college = college.set_index("INSTNM")
college_ugds_ = college.filter(like="UGDS_")
college_ugds_.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

<p><b>This recipe uses multiple operators with a DataFrame to round the undergraduate columns to the nearest hundredth. we sill then see how this result is equivalent to the round <i>method</i></b></p>

<p><b>1. To begin our rounding adventure with operators, we will first add <i>0.00501</i> to each value of <i>college_ugds_</i>:</p>

In [111]:
college_ugds_ + 0.00501

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.03831,0.94031,0.01051,0.00691,0.00741,0.00691,0.00501,0.01091,0.01881
University of Alabama at Birmingham,0.59721,0.26501,0.03331,0.05681,0.00721,0.00571,0.04181,0.02291,0.01501
Amridge University,0.30401,0.42421,0.01191,0.00841,0.00501,0.00501,0.00501,0.00501,0.27651
University of Alabama in Huntsville,0.70381,0.13051,0.04321,0.04261,0.01931,0.00521,0.02221,0.03821,0.04001
Alabama State University,0.02081,0.92581,0.01711,0.00691,0.00601,0.00561,0.01481,0.02931,0.01871
...,...,...,...,...,...,...,...,...,...
SAE Institute of Technology San Francisco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rasmussen College - Overland Park,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
National Personal Training Institute of Cleveland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bay Area Medical Academy - San Jose Satellite Location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Excel Learning Center-San Antonio South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<p><b>2. Use the floor division operator, <i>//</i>, to round to the nearest whole number percentage</b></p>

In [112]:
(college_ugds_ + 0.00501) // 0.01

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,3.0,94.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
University of Alabama at Birmingham,59.0,26.0,3.0,5.0,0.0,0.0,4.0,2.0,1.0
Amridge University,30.0,42.0,1.0,0.0,0.0,0.0,0.0,0.0,27.0
University of Alabama in Huntsville,70.0,13.0,4.0,4.0,1.0,0.0,2.0,3.0,4.0
Alabama State University,2.0,92.0,1.0,0.0,0.0,0.0,1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...
SAE Institute of Technology San Francisco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rasmussen College - Overland Park,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
National Personal Training Institute of Cleveland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bay Area Medical Academy - San Jose Satellite Location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Excel Learning Center-San Antonio South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<p><b>3. To complete the rounding exercise, divide by 100</b></p>

In [113]:
college_ugds_op_round = (college_ugds_ + 0.00501) // 0.01 / 100
college_ugds_op_round.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.03,0.94,0.01,0.00,0.00,0.0,0.00,0.01,0.01
University of Alabama at Birmingham,0.59,0.26,0.03,0.05,0.00,0.0,0.04,0.02,0.01
Amridge University,0.30,0.42,0.01,0.00,0.00,0.0,0.00,0.00,0.27
University of Alabama in Huntsville,0.70,0.13,0.04,0.04,0.01,0.0,0.02,0.03,0.04
Alabama State University,0.02,0.92,0.01,0.00,0.00,0.0,0.01,0.02,0.01

<p><b>4. Use the <i>round</i> method for rounding automaticallt for us</b></p>

In [114]:
college_ugds_round = (college_ugds_ + 0.00001).round(2)
college_ugds_round.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.03,0.94,0.01,0.00,0.00,0.0,0.00,0.01,0.01
University of Alabama at Birmingham,0.59,0.26,0.03,0.05,0.00,0.0,0.04,0.02,0.01
Amridge University,0.30,0.42,0.01,0.00,0.00,0.0,0.00,0.00,0.27
University of Alabama in Huntsville,0.70,0.13,0.04,0.04,0.01,0.0,0.02,0.03,0.04
Alabama State University,0.02,0.92,0.01,0.00,0.00,0.0,0.01,0.02,0.01

<p><b>Use the <i>equals</i> DataFrame method to test the equality of two DataFrames</p>

In [115]:
college_ugds_op_round.equals(college_ugds_round)

True

<center>
    <h3>Comparing missing values</h3>
</center>

<p>Pandas use the NumPy NaN (np.nan) object to represent a missing value. This is an unusual object, as it is not equal to itself</p>

In [116]:
import numpy as np

In [117]:
np.nan == np.nan

False

In [118]:
None == None

True

In [119]:
college.head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5

In [120]:
college_ugds_.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

<p><b>1. How the equals operator works</b></p>

In [121]:
college_ugds_ == 0.0019

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,False,False,False,True,False,True,False,False,False
University of Alabama at Birmingham,False,False,False,False,False,False,False,False,False
Amridge University,False,False,False,False,False,False,False,False,False
University of Alabama in Huntsville,False,False,False,False,False,False,False,False,False
Alabama State University,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
SAE Institute of Technology San Francisco,False,False,False,False,False,False,False,False,False
Rasmussen College - Overland Park,False,False,False,False,False,False,False,False,False
National Personal Training Institute of Cleveland,False,False,False,False,False,False,False,False,False
Bay Area Medical Academy - San Jose Satellite Location,False,False,False,False,False,False,False,False,False
Excel Learning Center-San Antonio South,False,False,False,False,False,False,False,False,False

<p><b>2. This work as expected but becomes problematic whenever you attempt to compare DataFrames with missing values</b></b>

In [122]:
college_self_compare = college_ugds_ == college_ugds_
college_self_compare.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,True,True,True,True,True,True,True,True,True
University of Alabama at Birmingham,True,True,True,True,True,True,True,True,True
Amridge University,True,True,True,True,True,True,True,True,True
University of Alabama in Huntsville,True,True,True,True,True,True,True,True,True
Alabama State University,True,True,True,True,True,True,True,True,True

<p><b>3. All the value appear to be equal, as you would expect. However, using the all method to determine if wach column contains only <i>True</i> values yileds an unexpected result</b></p>

In [123]:
college_self_compare.all()

UGDS_WHITE    False
UGDS_BLACK    False
UGDS_HISP     False
UGDS_ASIAN    False
UGDS_AIAN     False
UGDS_NHPI     False
UGDS_2MOR     False
UGDS_NRA      False
UGDS_UNKN     False
dtype: bool

<center>
    <b>4. This happends because missing values do not compare equally with one another. If you tried to count missing values using the equal operator and summing uo the boolean columns, you would get zero for each one</b>
</center>

In [124]:
(college_ugds_ == np.nan).sum()

UGDS_WHITE    0
UGDS_BLACK    0
UGDS_HISP     0
UGDS_ASIAN    0
UGDS_AIAN     0
UGDS_NHPI     0
UGDS_2MOR     0
UGDS_NRA      0
UGDS_UNKN     0
dtype: int64

<p><b>5. The primary way to count missing values uses the <i>isnull</i> method: </b></p>

In [125]:
college_ugds_.isnull().sum()

UGDS_WHITE    661
UGDS_BLACK    661
UGDS_HISP     661
UGDS_ASIAN    661
UGDS_AIAN     661
UGDS_NHPI     661
UGDS_2MOR     661
UGDS_NRA      661
UGDS_UNKN     661
dtype: int64

<center>
    <b>The correct way to comapre two entire DataFrames with one another is not with the equals operator but with the <i>equals</i> method</b>
</center>

In [126]:
college_ugds_.equals(college_ugds_)

True

<center>
    <h3>
        <b>Transposing the direction of a DataFrame operation</b>
    </h3>
</center>

<p>Many DataFrame methods have an <i>axis</i> parameter. This important parameter controls the direction in wich the operator takes place. Axis parameters can only be one o two values, etiher 0 or 1, and are aliased respectively as the string <i>index</i> and <i>columns</i></p>

<ul>
    <li>0 = index</li>
    <li>1 = columns</li>
</ul>

<p><b>1. We need to use the same 2 DataFrames front the last exercise</b></p>

In [127]:
college.head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5

In [128]:
college_ugds_.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

<b>2. the <i>count</i> method returns the number of non-missing values. By default, its <i>axis</i> parameter is set to 0</b>

In [129]:
college_ugds_.count()

UGDS_WHITE    6874
UGDS_BLACK    6874
UGDS_HISP     6874
UGDS_ASIAN    6874
UGDS_AIAN     6874
UGDS_NHPI     6874
UGDS_2MOR     6874
UGDS_NRA      6874
UGDS_UNKN     6874
dtype: int64

<b>3. Changing the <i>axis</i> parameter to 1/columns transposes the operation so taht each row of data has a count of its non-missing values:</b>

In [130]:
college_ugds_.count(axis="columns").head()

INSTNM
Alabama A & M University               9
University of Alabama at Birmingham    9
Amridge University                     9
University of Alabama in Huntsville    9
Alabama State University               9
dtype: int64

In [131]:
college_ugds_.count(axis=1).head()

INSTNM
Alabama A & M University               9
University of Alabama at Birmingham    9
Amridge University                     9
University of Alabama in Huntsville    9
Alabama State University               9
dtype: int64

<b>4. Instead of counting non-missing values, we can sum all the values, we can sume all the vakues in each row of percentahes should add up to 1.</b>

In [132]:
college_ugds_.sum(axis="columns").head()

INSTNM
Alabama A & M University               1.0000
University of Alabama at Birmingham    0.9999
Amridge University                     1.0000
University of Alabama in Huntsville    1.0000
Alabama State University               1.0000
dtype: float64

<b>5. To get an idea of the distribution of wach column, the <i>median</i> method can be used:</b>

In [133]:
college_ugds_.median(axis="index")

UGDS_WHITE    0.55570
UGDS_BLACK    0.10005
UGDS_HISP     0.07140
UGDS_ASIAN    0.01290
UGDS_AIAN     0.00260
UGDS_NHPI     0.00000
UGDS_2MOR     0.01750
UGDS_NRA      0.00000
UGDS_UNKN     0.01430
dtype: float64

<center>
    <h4>
        <b>Determine college campis diversity</b>
    </h4>
</center>

<p> <b> 1. Count all the missing values fir each row and wort the results </b> </p>

In [134]:
college_ugds_.isnull().sum(axis=1).sort_values(ascending=False).head()

INSTNM
Strayer University-Columbia Campus               9
Teachers College at Columbia University          9
Excel Learning Center-San Antonio South          9
Trinity Law School                               9
Saint Vladimirs Orthodox Theological Seminary    9
dtype: int64

<p><b>2. Use the dropna.() method to drop all rows that have all nine race percentages missing</b></p>

In [135]:
college_ugds_ = college_ugds_.dropna(how="all")
college_ugds_.isnull().sum()

UGDS_WHITE    0
UGDS_BLACK    0
UGDS_HISP     0
UGDS_ASIAN    0
UGDS_AIAN     0
UGDS_NHPI     0
UGDS_2MOR     0
UGDS_NRA      0
UGDS_UNKN     0
dtype: int64

<table>
    <thead>
        <tr>
            <th>Valor</th>
            <th>Significado</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><i>"any"</i></td>
            <td>Elimina la fila/columna si <b>al menos un </b> valor es NaN</td>
        </tr>
    </tbody>
    <tbody>
        <tr>
            <td><i>"all"</i></td>
            <td>Elimina la fila/columna <b>si todos</b> los valores son NaN</td>
        </tr>
    </tbody>
</table>

<b>3. We will use the greater tahn or equal DataFrame method, <i>get</i>, to convert each value to a boolean:</b>

In [136]:
college_ugds_.ge(.15).head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,False,True,False,False,False,False,False,False,False
University of Alabama at Birmingham,True,True,False,False,False,False,False,False,False
Amridge University,True,True,False,False,False,False,False,False,True
University of Alabama in Huntsville,True,False,False,False,False,False,False,False,False
Alabama State University,False,True,False,False,False,False,False,False,False

<b>4. we can use the <i>sum</i> method to count the <i>True</i> values for watch college</b>

In [137]:
diversity_metric = college_ugds_.ge(.15).sum(axis=1)
diversity_metric.head()

INSTNM
Alabama A & M University               1
University of Alabama at Birmingham    2
Amridge University                     3
University of Alabama in Huntsville    1
Alabama State University               1
dtype: int64

<b>5. To get an idea of the distribution, let's use the <i>value_counts</i> method on this Series</b>

In [138]:
diversity_metric.value_counts()

1    3042
2    2884
3     876
4      63
0       7
5       2
Name: count, dtype: int64

<b>6. two schools have more than 15% in five different race categories</b>

In [139]:
diversity_metric.sort_values(ascending=False).head()

INSTNM
Central Texas Beauty College-Temple      5
Regency Beauty Institute-Austin          5
Northwood University-Texas               4
Laney College                            4
Sullivan and Cogliano Training Center    4
dtype: int64

<b>7. Let's look at the raw percentages from these top two schools with the <i>.loc</i> indexer</b>

In [140]:
college_ugds_.loc[["Regency Beauty Institute-Austin", "Central Texas Beauty College-Temple"]]

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Regency Beauty Institute-Austin,0.1867,0.2133,0.1600,0.0000,0.0,0.0,0.1733,0.0,0.2667
Central Texas Beauty College-Temple,0.1616,0.2323,0.2626,0.0202,0.0,0.0,0.1717,0.0,0.1515

<b> 8. We can see how the top 10 US- News schools fared with this basic diversity metric</b>

In [141]:
us_news_top = ["Rutgers University-Newark", 
               "Andrews University", 
               "Stanford University",
               "University of Houston",
               "University of Nevada-Las Vegas"] 

diversity_metric.loc[us_news_top]

INSTNM
Rutgers University-Newark         4
Andrews University                3
Stanford University               3
University of Houston             3
University of Nevada-Las Vegas    3
dtype: int64

<center>
    <h1>
        <b>Beginning Data Analysis</b>
    </h1>
</center>

<h4>Analysis Routine</h4>

<ol>
    <li> <b>read_csv</b> --> Read Dataset</li>
    <li> <b>.shape</b> --> Dimension</li>
    <li> <b>info()</b> --> Data type of each column</li>
    <li> <b>.describe</b> --> Statistics of the numerical columns</li>
</ol>

<b>1. Read in the DataSet</b>

In [142]:
college.head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5

<b>2. Get the dimension of the DataFrame</b>

In [143]:
college.shape

(7535, 26)

<b>3. List the data type of each column</b>

In [144]:
college.info()

<class 'pandas.DataFrame'>
Index: 7535 entries, Alabama A & M University to Excel Learning Center-San Antonio South
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CITY                7535 non-null   str
 1   STABBR              7535 non-null   str
 2   HBCU                7164 non-null   float64
 3   MENONLY             7164 non-null   float64
 4   WOMENONLY           7164 non-null   float64
 5   RELAFFIL            7535 non-null   int64
 6   SATVRMID            1185 non-null   float64
 7   SATMTMID            1196 non-null   float64
 8   DISTANCEONLY        7164 non-null   float64
 9   UGDS                6874 non-null   float64
 10  UGDS_WHITE          6874 non-null   float64
 11  UGDS_BLACK          6874 non-null   float64
 12  UGDS_HISP           6874 non-null   float64
 13  UGDS_ASIAN          6874 non-null   float64
 14  UGDS_AIAN           6874 non-null   float64
 15  UGDS_NHPI           6874 non-null   float64
 16  UGDS_2MOR           6874 non-null   float64
 17  UGDS_NRA            6874 non-null   float64
 18  UGDS_UNKN           6874 non-null   float64
 19  PPTUG_EF            6853 non-null   float64
 20  CURROPER            7535 non-null   int64
 21  PCTPELL             6849 non-null   float64
 22  PCTFLOAN            6849 non-null   float64
 23  UG25ABV             6718 non-null   float64
 24  MD_EARN_WNE_P10     6413 non-null   str
 25  GRAD_DEBT_MDN_SUPP  7503 non-null   str
dtypes: float64(20), int64(2), str(4)
memory usage: 1.8+ MB

<b>4. Get summary statistics for the numerical columns and transpose the DataFrame for more readable output</b>

In [145]:
college.describe(include=[np.number]).transpose()

,count,mean,std,min,25%,50%,75%,max
HBCU,7164.0,0.014238,0.118478,0.0,0.000000,0.00000,0.000000,1.0000
MENONLY,7164.0,0.009213,0.095546,0.0,0.000000,0.00000,0.000000,1.0000
WOMENONLY,7164.0,0.005304,0.072642,0.0,0.000000,0.00000,0.000000,1.0000
RELAFFIL,7535.0,0.190975,0.393096,0.0,0.000000,0.00000,0.000000,1.0000
SATVRMID,1185.0,522.819409,68.578862,290.0,475.000000,510.00000,555.000000,765.0000
SATMTMID,1196.0,530.765050,73.469767,310.0,482.000000,520.00000,565.000000,785.0000
DISTANCEONLY,7164.0,0.005583,0.074519,0.0,0.000000,0.00000,0.000000,1.0000
UGDS,6874.0,2356.837940,5474.275871,0.0,117.000000,412.50000,1929.500000,151558.0000
UGDS_WHITE,6874.0,0.510207,0.286958,0.0,0.267500,0.55570,0.747875,1.0000
UGDS_BLACK,6874.0,0.189997,0.224587,0.0,0.036125,0.10005,0.257700,1.0000
UGDS_HISP,6874.0,0.161635,0.221854,0.0,0.027600,0.07140,0.198875,1.0000
UGDS_ASIAN,6874.0,0.033544,0.073777,0.0,0.002500,0.01290,0.032700,0.9727
UGDS_AIAN,6874.0,0.013813,0.070196,0.0,0.000000,0.00260,0.007300,1.0000
UGDS_NHPI,6874.0,0.004569,0.033125,0.0,0.000000,0.00000,0.002500,0.9983
UGDS_2MOR,6874.0,0.023950,0.031288,0.0,0.000000,0.01750,0.033900,0.5333
UGDS_NRA,6874.0,0.016086,0.050172,0.0,0.000000,0.00000,0.011700,0.9286
UGDS_UNKN,6874.0,0.045181,0.093440,0.0,0.000000,0.01430,0.045400,0.9027
PPTUG_EF,6853.0,0.226639,0.246470,0.0,0.000000,0.15040,0.376900,1.0000
CURROPER,7535.0,0.923291,0.266146,0.0,1.000000,1.00000,1.000000,1.0000
PCTPELL,6849.0,0.530643,0.225544,0.0,0.357800,0.52150,0.712900,1.0000
PCTFLOAN,6849.0,0.522211,0.283616,0.0,0.332900,0.58330,0.745000,1.0000
UG25ABV,6718.0,0.410021,0.228939,0.0,0.241500,0.40075,0.572275,1.0000

<b>5. Get summary statistics for the object and categorical columns</b>

In [146]:
college.describe(include=[np.number, pd.Categorical]).transpose()

C:\Users\uih30853\AppData\Local\Temp\ipykernel_11132\1795950075.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  college.describe(include=[np.number, pd.Categorical]).transpose()

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
CITY,7535,2514,New York,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
STABBR,7535,59,CA,773,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HBCU,7164.0,NaN,NaN,NaN,0.014238,0.118478,0.0,0.0,0.0,0.0,1.0
MENONLY,7164.0,NaN,NaN,NaN,0.009213,0.095546,0.0,0.0,0.0,0.0,1.0
WOMENONLY,7164.0,NaN,NaN,NaN,0.005304,0.072642,0.0,0.0,0.0,0.0,1.0
RELAFFIL,7535.0,NaN,NaN,NaN,0.190975,0.393096,0.0,0.0,0.0,0.0,1.0
SATVRMID,1185.0,NaN,NaN,NaN,522.819409,68.578862,290.0,475.0,510.0,555.0,765.0
SATMTMID,1196.0,NaN,NaN,NaN,530.76505,73.469767,310.0,482.0,520.0,565.0,785.0
DISTANCEONLY,7164.0,NaN,NaN,NaN,0.005583,0.074519,0.0,0.0,0.0,0.0,1.0
UGDS,6874.0,NaN,NaN,NaN,2356.83794,5474.275871,0.0,117.0,412.5,1929.5,151558.0
UGDS_WHITE,6874.0,NaN,NaN,NaN,0.510207,0.286958,0.0,0.2675,0.5557,0.747875,1.0
UGDS_BLACK,6874.0,NaN,NaN,NaN,0.189997,0.224587,0.0,0.036125,0.10005,0.2577,1.0
UGDS_HISP,6874.0,NaN,NaN,NaN,0.161635,0.221854,0.0,0.0276,0.0714,0.198875,1.0
UGDS_ASIAN,6874.0,NaN,NaN,NaN,0.033544,0.073777,0.0,0.0025,0.0129,0.0327,0.9727
UGDS_AIAN,6874.0,NaN,NaN,NaN,0.013813,0.070196,0.0,0.0,0.0026,0.0073,1.0
UGDS_NHPI,6874.0,NaN,NaN,NaN,0.004569,0.033125,0.0,0.0,0.0,0.0025,0.9983
UGDS_2MOR,6874.0,NaN,NaN,NaN,0.02395,0.031288,0.0,0.0,0.0175,0.0339,0.5333
UGDS_NRA,6874.0,NaN,NaN,NaN,0.016086,0.050172,0.0,0.0,0.0,0.0117,0.9286
UGDS_UNKN,6874.0,NaN,NaN,NaN,0.045181,0.09344,0.0,0.0,0.0143,0.0454,0.9027
PPTUG_EF,6853.0,NaN,NaN,NaN,0.226639,0.24647,0.0,0.0,0.1504,0.3769,1.0
CURROPER,7535.0,NaN,NaN,NaN,0.923291,0.266146,0.0,1.0,1.0,1.0,1.0
PCTPELL,6849.0,NaN,NaN,NaN,0.530643,0.225544,0.0,0.3578,0.5215,0.7129,1.0
PCTFLOAN,6849.0,NaN,NaN,NaN,0.522211,0.283616,0.0,0.3329,0.5833,0.745,1.0
UG25ABV,6718.0,NaN,NaN,NaN,0.410021,0.228939,0.0,0.2415,0.40075,0.572275,1.0
MD_EARN_WNE_P10,6413,598,PrivacySuppressed,822,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GRAD_DEBT_MDN_SUPP,7503,2038,PrivacySuppressed,1510,NaN,NaN,NaN,NaN,NaN,NaN,NaN