<center>
    <h1>Exploring and pre-processing a dataset using Pandas</h1>
</center>

<i>We need to install <b>openpyxl</i>, a module that pandas requires to read Excel files</i>

In [3]:
pip install -q openpyxl

Note: you may need to restart the kernel to use updated packages.

<i>Next, we have to import two key data analysis modules: pandas and numpy</i>

In [5]:
pip install -q pandas

Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install -q numpy

Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd
import numpy as np

<i>Let's donwnload and import our primary Canadian Inmigration dataset using panda's <b>read_excel()</b> method</i>

In [12]:
df_can = pd.read_excel("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/Canada.xlsx",
                       sheet_name="Canada by Citizenship",
                       skiprows=range(20),
                       skipfooter=2)

print("Data read into a pandas DataFrame!")

Data read into a pandas DataFrame!

In [14]:
df_can.head()

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1

<i>We can also view the bottom 5 rows of the dataset using the <b>tail()</b> function</i>

In [18]:
df_can.tail()

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
190,Immigrants,Foreigners,Viet Nam,935,Asia,920,South-Eastern Asia,902,Developing regions,1191,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
191,Immigrants,Foreigners,Western Sahara,903,Africa,912,Northern Africa,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
192,Immigrants,Foreigners,Yemen,935,Asia,922,Western Asia,902,Developing regions,1,...,124,161,140,122,133,128,211,160,174,217
193,Immigrants,Foreigners,Zambia,903,Africa,910,Eastern Africa,902,Developing regions,11,...,56,91,77,71,64,60,102,69,46,59
194,Immigrants,Foreigners,Zimbabwe,903,Africa,910,Eastern Africa,902,Developing regions,72,...,1450,615,454,663,611,508,494,434,437,407

<i>When we analize a dataset, it's always a good idea to start by getting basic information about your dataframe, we can do this using the <b>info()</b> method</i>

In [21]:
df_can.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 43 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Type      195 non-null    object
 1   Coverage  195 non-null    object
 2   OdName    195 non-null    object
 3   AREA      195 non-null    int64
 4   AreaName  195 non-null    object
 5   REG       195 non-null    int64
 6   RegName   195 non-null    object
 7   DEV       195 non-null    int64
 8   DevName   195 non-null    object
 9   1980      195 non-null    int64
 10  1981      195 non-null    int64
 11  1982      195 non-null    int64
 12  1983      195 non-null    int64
 13  1984      195 non-null    int64
 14  1985      195 non-null    int64
 15  1986      195 non-null    int64
 16  1987      195 non-null    int64
 17  1988      195 non-null    int64
 18  1989      195 non-null    int64
 19  1990      195 non-null    int64
 20  1991      195 non-null    int64
 21  1992      195 non-null    int64
 22  1993      195 non-null    int64
 23  1994      195 non-null    int64
 24  1995      195 non-null    int64
 25  1996      195 non-null    int64
 26  1997      195 non-null    int64
 27  1998      195 non-null    int64
 28  1999      195 non-null    int64
 29  2000      195 non-null    int64
 30  2001      195 non-null    int64
 31  2002      195 non-null    int64
 32  2003      195 non-null    int64
 33  2004      195 non-null    int64
 34  2005      195 non-null    int64
 35  2006      195 non-null    int64
 36  2007      195 non-null    int64
 37  2008      195 non-null    int64
 38  2009      195 non-null    int64
 39  2010      195 non-null    int64
 40  2011      195 non-null    int64
 41  2012      195 non-null    int64
 42  2013      195 non-null    int64
dtypes: int64(37), object(6)
memory usage: 65.6+ KB

<i>To get the list of columns headers we can call upon the dataframe <b>columns</b> instance variable</i>

In [24]:
df_can.columns

Index([    'Type', 'Coverage',   'OdName',     'AREA', 'AreaName',      'REG',
        'RegName',      'DEV',  'DevName',       1980,       1981,       1982,
             1983,       1984,       1985,       1986,       1987,       1988,
             1989,       1990,       1991,       1992,       1993,       1994,
             1995,       1996,       1997,       1998,       1999,       2000,
             2001,       2002,       2003,       2004,       2005,       2006,
             2007,       2008,       2009,       2010,       2011,       2012,
             2013],
      dtype='object')

<i>Similarly, to get a list of indices we use the <b>.index</b> instance variables</i>

In [26]:
df_can.index

RangeIndex(start=0, stop=195, step=1)

<i>The default type os intance variables index and columns are not lists</i>

In [28]:
print(type(df_can.columns))
print(type(df_can.index))

<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.range.RangeIndex'>

<i>To get the index and columns as lists, we can use the <b>tolist()</b> method

In [30]:
df_can.columns.tolist()

['Type',
 'Coverage',
 'OdName',
 'AREA',
 'AreaName',
 'REG',
 'RegName',
 'DEV',
 'DevName',
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013]

In [32]:
df_can.index.tolist()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194]

In [34]:
print(type(df_can.columns.tolist()))
print(type(df_can.columns.tolist()))

<class 'list'>
<class 'list'>

<i>To view the dimensions of the dataframe, we use the <b>shape</b> instance variable of it</i>

In [37]:
df_can.shape

(195, 43)

<p><b>NOTE:</b>: The main types stored in <i>pandas</i> objects are <b>float, int, bool, datetime64[ns], datetime64[ns, tz], timedelta[ns], category, </b> and <b>object</b> (string). In addition, the dtypes have items sizes.</p>

<p>Let's clean the dataset to remove a few unnecessary columns. We can use <i>pandas</i> <b>drop()</b> method as follows</p>

In [41]:
df_can.drop(["AREA", "REG", "DEV", "Type", "Coverage"], axis=1, inplace=True, errors="ignore")
df_can.head(2)

,OdName,AreaName,RegName,DevName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1450,1223,856,702,560,716,561,539,620,603

<p>Let's rename the columns so that they make sense. We can use <b>rename()</b> method by passing in a dictionart fo old new name as follows </p>

In [43]:
df_can.rename(columns={"OdName":"Country","AreaName":"Continent","RegName":"Region"}, inplace=True)
df_can.columns

Index([  'Country', 'Continent',    'Region',   'DevName',        1980,
              1981,        1982,        1983,        1984,        1985,
              1986,        1987,        1988,        1989,        1990,
              1991,        1992,        1993,        1994,        1995,
              1996,        1997,        1998,        1999,        2000,
              2001,        2002,        2003,        2004,        2005,
              2006,        2007,        2008,        2009,        2010,
              2011,        2012,        2013],
      dtype='object')

<p>We sill also add a "Total" columns that sums up the total inmigrants by country over the entire period 1980 - 2013, as follows</p>

In [47]:
df_can['Total'] = df_can.sum(axis=1, numeric_only=True)
df_can['Total']

0      117278
1       31398
2      138878
3          12
4          30
        ...
190    194292
191         4
192      5970
193      3354
194     17196
Name: Total, Length: 195, dtype: int64

<p>We can check to see how many null objects we have in the dataset as follows</p>

In [49]:
df_can.isnull().sum()

Country      0
Continent    0
Region       0
DevName      0
1980         0
1981         0
1982         0
1983         0
1984         0
1985         0
1986         0
1987         0
1988         0
1989         0
1990         0
1991         0
1992         0
1993         0
1994         0
1995         0
1996         0
1997         0
1998         0
1999         0
2000         0
2001         0
2002         0
2003         0
2004         0
2005         0
2006         0
2007         0
2008         0
2009         0
2010         0
2011         0
2012         0
2013         0
Total        0
dtype: int64

<p>Finally, let's view a quick summary of wach column is our datafram using the <b>describe()</b> method</p>

In [51]:
df_can.describe()

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
count,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,...,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,1.950000e+02
mean,508.394872,566.989744,534.723077,387.435897,376.497436,358.861538,441.271795,691.133333,714.389744,843.241026,...,1320.292308,1266.958974,1191.820513,1246.394872,1275.733333,1420.287179,1262.533333,1313.958974,1320.702564,6.573490e+04
std,1949.588546,2152.643752,1866.997511,1204.333597,1198.246371,1079.309600,1225.576630,2109.205607,2443.606788,2555.048874,...,4425.957828,3926.717747,3443.542409,3694.573544,3829.630424,4462.946328,4030.084313,4247.555161,4237.951988,1.835710e+05
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000e+00
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.500000,1.000000,1.000000,...,28.500000,25.000000,31.000000,31.000000,36.000000,40.500000,37.500000,42.500000,45.000000,1.904000e+03
50%,13.000000,10.000000,11.000000,12.000000,13.000000,17.000000,18.000000,26.000000,34.000000,44.000000,...,210.000000,218.000000,198.000000,205.000000,214.000000,211.000000,179.000000,233.000000,213.000000,1.003600e+04
75%,251.500000,295.500000,275.000000,173.000000,181.000000,197.000000,254.000000,434.000000,409.000000,508.500000,...,832.000000,842.000000,899.000000,934.500000,888.000000,932.000000,772.000000,783.000000,796.000000,4.447900e+04
max,22045.000000,24796.000000,20620.000000,10015.000000,10170.000000,9564.000000,9470.000000,21337.000000,27359.000000,23795.000000,...,42584.000000,33848.000000,28742.000000,30037.000000,29622.000000,38617.000000,36765.000000,34315.000000,34129.000000,1.383808e+06

<center>
    <h2><i>pandas</i> Intermediate: Indexiing and Selection (slicing)</h2>
</center>

<h4><b>Select Column</b></h4>
<p></p><b>There're two ways to filter on a column name</b></p>

<p>Only works if the column name does not have spaces or special characters</p>
<ul>
    <li>df.column_name --> Returns series</li>
</ul>

<p>More robust, and can filter on multiple columns</p>
<ul>
    <li>df["column"] --> Returns series</li>
    <li>df[["columns", "column2"] --> Returns dataframe</li>
</ul>

<i>Example: Let's try filtering on the list of countries ("Country")

In [53]:
df_can.Country

0         Afghanistan
1             Albania
2             Algeria
3      American Samoa
4             Andorra
            ...
190          Viet Nam
191    Western Sahara
192             Yemen
193            Zambia
194          Zimbabwe
Name: Country, Length: 195, dtype: object

<i>Let's try filtering on the list of countries ("Country") and the data for years: 1980 - 1985.</i>

In [55]:
df_can[["Country", 1980, 1981, 1982, 1983, 1984, 1985]]

            Country  1980  1981  1982  1983  1984  1985
0       Afghanistan    16    39    39    47    71   340
1           Albania     1     0     0     0     0     0
2           Algeria    80    67    71    69    63    44
3    American Samoa     0     1     0     0     0     0
4           Andorra     0     0     0     0     0     0
..              ...   ...   ...   ...   ...   ...   ...
190        Viet Nam  1191  1829  2162  3404  7583  5907
191  Western Sahara     0     0     0     0     0     0
192           Yemen     1     2     1     6     0    18
193          Zambia    11    17    11     7    16     9
194        Zimbabwe    72   114   102    44    32    29

[195 rows x 7 columns]

<h4><b>Select rows</b></h4>
<p>There are main 2 ways to select rows</p>

<ul>
    <li>df.loc[label] --> filters by the labels of the index/column</li>
    <li>df.iloc[index] --> filters by the positions of the index/column</li>
</ul>

<p>Before we proceed, notice that default index of the dataset is a numeric range from 0 to 194. This makes it very dificult to do a query by a specific cuntry. Fro example to search for data on Japan, we need to know the corresponding index value</p>

<p>Thsi can be fixed very easily by setting the "Country" coolumn as the index using <b>set_index()</b> method</p>

In [65]:
df_can.set_index("Country", inplace=True, )

In [68]:
df_can.head(5)

,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,1986,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,496,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,117278
Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,1,...,1223,856,702,560,716,561,539,620,603,31398
Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,69,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,138878
American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,12
Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,2,...,0,1,1,0,0,0,0,1,1,30

<i>To remove the anme of the index</i>

In [70]:
df_can.index.name = None

<p>Example: Let's view the numer of inmigrants from Japan for the following scenarios:</p>
<ul>
    <li>1. The full row data (all columns)</li>
    <li>2. For yeat 2013</li>
    <li>3. For years 1980 to 1985</li>
</ul>

<center>
</h4><b>1. The full raw data</b></h4>
</center>

In [72]:
df_can.loc["Japan"]

Continent                 Asia
Region            Eastern Asia
DevName      Developed regions
1980                       701
1981                       756
1982                       598
1983                       309
1984                       246
1985                       198
1986                       248
1987                       422
1988                       324
1989                       494
1990                       379
1991                       506
1992                       605
1993                       907
1994                       956
1995                       826
1996                       994
1997                       924
1998                       897
1999                      1083
2000                      1010
2001                      1092
2002                       806
2003                       817
2004                       973
2005                      1067
2006                      1212
2007                      1250
2008                      1284
2009                      1194
2010                      1168
2011                      1265
2012                      1214
2013                       982
Total                    55414
Name: Japan, dtype: object

<b>Alternative methods</b>

In [75]:
df_can.iloc[87]

Continent                 Asia
Region            Eastern Asia
DevName      Developed regions
1980                       701
1981                       756
1982                       598
1983                       309
1984                       246
1985                       198
1986                       248
1987                       422
1988                       324
1989                       494
1990                       379
1991                       506
1992                       605
1993                       907
1994                       956
1995                       826
1996                       994
1997                       924
1998                       897
1999                      1083
2000                      1010
2001                      1092
2002                       806
2003                       817
2004                       973
2005                      1067
2006                      1212
2007                      1250
2008                      1284
2009                      1194
2010                      1168
2011                      1265
2012                      1214
2013                       982
Total                    55414
Name: Japan, dtype: object

In [77]:
df_can.iloc[87]

Continent                 Asia
Region            Eastern Asia
DevName      Developed regions
1980                       701
1981                       756
1982                       598
1983                       309
1984                       246
1985                       198
1986                       248
1987                       422
1988                       324
1989                       494
1990                       379
1991                       506
1992                       605
1993                       907
1994                       956
1995                       826
1996                       994
1997                       924
1998                       897
1999                      1083
2000                      1010
2001                      1092
2002                       806
2003                       817
2004                       973
2005                      1067
2006                      1212
2007                      1250
2008                      1284
2009                      1194
2010                      1168
2011                      1265
2012                      1214
2013                       982
Total                    55414
Name: Japan, dtype: object

In [79]:
df_can.iloc[87]

Continent                 Asia
Region            Eastern Asia
DevName      Developed regions
1980                       701
1981                       756
1982                       598
1983                       309
1984                       246
1985                       198
1986                       248
1987                       422
1988                       324
1989                       494
1990                       379
1991                       506
1992                       605
1993                       907
1994                       956
1995                       826
1996                       994
1997                       924
1998                       897
1999                      1083
2000                      1010
2001                      1092
2002                       806
2003                       817
2004                       973
2005                      1067
2006                      1212
2007                      1250
2008                      1284
2009                      1194
2010                      1168
2011                      1265
2012                      1214
2013                       982
Total                    55414
Name: Japan, dtype: object

In [82]:
df_can[df_can.index == "Japan"]

,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,1986,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Japan,Asia,Eastern Asia,Developed regions,701,756,598,309,246,198,248,...,1067,1212,1250,1284,1194,1168,1265,1214,982,55414

<center>
<h4><b>2. For year 2013</b></h4>
</center>

In [85]:
df_can.loc["Japan", 2013]

np.int64(982)

In [87]:
df_can.iloc[87, 36]

np.int64(982)

<center>
    <h4><b>3. For the years 1980 to 1985</b></h4>
</center>

In [92]:
df_can.loc["Japan", [1980, 1981, 1982, 1983, 1984, 1985]]

1980    701
1981    756
1982    598
1983    309
1984    246
1985    198
Name: Japan, dtype: object

In [93]:
df_can.iloc[87, [3,4,5,6,7,8]]

1980    701
1981    756
1982    598
1983    309
1984    246
1985    198
Name: Japan, dtype: object

<p><b>Exercise</b>: Let's view the number of inmigrants from <b>Haiti</b> for the following scenarios:</p>
<ul>
    <li>The full row of data (all columns)</li>
    <li>For year 2000</li>
    <li>For years 1990 to 1995</li>
</ul>

In [96]:
df_can.loc["Haiti"]

Continent    Latin America and the Caribbean
Region                             Caribbean
DevName                   Developing regions
1980                                    1666
1981                                    3692
1982                                    3498
1983                                    2860
1984                                    1418
1985                                    1321
1986                                    1753
1987                                    2132
1988                                    1829
1989                                    2377
1990                                    2379
1991                                    2829
1992                                    2399
1993                                    3655
1994                                    2100
1995                                    2014
1996                                    1955
1997                                    1645
1998                                    1295
1999                                    1439
2000                                    1631
2001                                    2433
2002                                    2174
2003                                    1930
2004                                    1652
2005                                    1682
2006                                    1619
2007                                    1598
2008                                    2491
2009                                    2080
2010                                    4744
2011                                    6503
2012                                    5868
2013                                    4152
Total                                 169626
Name: Haiti, dtype: object

In [98]:
df_can.loc["Haiti", 2000]

np.int64(1631)

In [100]:
df_can.loc["Haiti", [1990, 1991, 1992, 1993, 1994, 1995]]

1990    2379
1991    2829
1992    2399
1993    3655
1994    2100
1995    2014
Name: Haiti, dtype: object

<p>Column name that are integers (such as the years) might introduce some confusion. For example, when we are referencing the year 2013, one might confuse that when the 2013th positional index<p>

<p>To avoidd this amguigity, let's convert the column names into strings: "1980" to "2013"</p>

In [103]:
df_can.columns = list(map(str, df_can.columns))

Since we converted the years to string, let's declare a variable that swill allow us to easly call upon the full range of years

In [107]:
years = list(map(str, range(1980, 2014)))
years

['1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013']

<p><b>Exercise:</b> Create a list named "year" using the map function for years ranging from 1990 to 2013. _Then extract the data series from the dataframe df_can for Haiti using year list</p>

In [112]:
year = list(map(str, range(1990, 2014)))
haiti = df_can.loc["Haiti", year]
haiti.head

<bound method NDFrame.head of 1990    2379
1991    2829
1992    2399
1993    3655
1994    2100
1995    2014
1996    1955
1997    1645
1998    1295
1999    1439
2000    1631
2001    2433
2002    2174
2003    1930
2004    1652
2005    1682
2006    1619
2007    1598
2008    2491
2009    2080
2010    4744
2011    6503
2012    5868
2013    4152
Name: Haiti, dtype: object>

<h3><b>Filtering based on a criteria</b></h3>
<p>To filter the dataframe based on a condition, we simply pass the condition as a boolean vector</p>
<p>For example, let's filter the dataframe to whos the data on Asian Countries (AreaName = Asia)</p>

In [115]:
condition = df_can["Continent"] == "Asia"
print(condition)

Afghanistan        True
Albania           False
Algeria           False
American Samoa    False
Andorra           False
                  ...
Viet Nam           True
Western Sahara    False
Yemen              True
Zambia            False
Zimbabwe          False
Name: Continent, Length: 195, dtype: bool

In [117]:
df_can[condition]

,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,1986,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,496,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,117278
Armenia,Asia,Western Asia,Developing regions,0,0,0,0,0,0,0,...,224,218,198,205,267,252,236,258,207,6620
Azerbaijan,Asia,Western Asia,Developing regions,0,0,0,0,0,0,0,...,359,236,203,125,165,209,138,161,57,5298
Bahrain,Asia,Western Asia,Developing regions,0,2,1,1,1,3,0,...,12,12,22,9,35,28,21,39,32,950
Bangladesh,Asia,Southern Asia,Developing regions,83,84,86,81,98,92,486,...,4171,4014,2897,2939,2104,4721,2694,2640,3789,131136
Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,...,5,10,7,36,865,1464,1879,1075,487,11752
Brunei Darussalam,Asia,South-Eastern Asia,Developing regions,79,6,8,2,2,4,12,...,4,5,11,10,5,12,6,3,6,1200
Cambodia,Asia,South-Eastern Asia,Developing regions,12,19,26,33,10,7,8,...,370,529,460,354,203,200,196,233,288,13076
China,Asia,Eastern Asia,Developing regions,5123,6682,3308,1863,1527,1816,1960,...,42584,33518,27642,30037,29622,30391,28502,33024,34129,1319924
"China, Hong Kong Special Administrative Region",Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,0,...,729,712,674,897,657,623,591,728,774,18654
"China, Macao Special Administrative Region",Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,0,...,21,32,16,12,21,21,13,33,29,568
Cyprus,Asia,Western Asia,Developing regions,132,128,84,46,46,43,48,...,7,9,4,7,6,18,6,12,16,2252
Democratic People's Republic of Korea,Asia,Eastern Asia,Developing regions,1,1,3,1,4,3,0,...,14,10,7,19,11,45,97,66,17,776
Georgia,Asia,Western Asia,Developing regions,0,0,0,0,0,0,0,...,114,125,132,112,128,126,139,147,125,4136
India,Asia,Southern Asia,Developing regions,8880,8670,8147,7338,5704,4211,7150,...,36210,33848,28742,28261,29456,34235,27509,30933,33087,1383808
Indonesia,Asia,South-Eastern Asia,Developing regions,186,178,252,115,123,100,127,...,632,613,657,661,504,712,390,395,387,26300
Iran (Islamic Republic of),Asia,Southern Asia,Developing regions,1172,1429,1822,1592,1977,1648,1794,...,5837,7480,6974,6475,6580,7477,7479,7534,11291,351846
Iraq,Asia,Western Asia,Developing regions,262,245,260,380,428,231,265,...,2226,1788,2406,3543,5450,5941,6196,4041,4918,139578
Israel,Asia,Western Asia,Developing regions,1403,1711,1334,541,446,680,1212,...,2446,2625,2401,2562,2316,2755,1970,2134,1945,133016
Japan,Asia,Eastern Asia,Developed regions,701,756,598,309,246,198,248,...,1067,1212,1250,1284,1194,1168,1265,1214,982,55414
Jordan,Asia,Western Asia,Developing regions,177,160,155,113,102,179,181,...,1940,1827,1421,1581,1235,1831,1635,1206,1255,70812
Kazakhstan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,0,...,506,408,436,394,431,377,381,462,348,16980
Kuwait,Asia,Western Asia,Developing regions,1,0,8,2,1,4,4,...,66,35,62,53,68,67,58,73,48,4050
Kyrgyzstan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,0,...,173,161,135,168,173,157,159,278,123,4706
Lao People's Democratic Republic,Asia,South-Eastern Asia,Developing regions,11,6,16,16,7,17,21,...,42,74,53,32,39,54,22,25,15,2178
Lebanon,Asia,Western Asia,Developing regions,1409,1119,1159,789,1253,1683,2576,...,3709,3802,3467,3566,3077,3432,3072,1614,2172,230718
Malaysia,Asia,South-Eastern Asia,Developing regions,786,816,813,448,384,374,425,...,593,580,600,658,640,802,409,358,204,48834
Maldives,Asia,Southern Asia,Developing regions,0,0,0,1,0,0,0,...,0,0,2,1,7,4,3,1,1,60
Mongolia,Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,0,...,59,64,82,59,118,169,103,68,99,1904
Myanmar,Asia,South-Eastern Asia,Developing regions,80,62,46,31,41,23,18,...,210,953,1887,975,1153,556,368,193,262,18490
Nepal,Asia,Southern Asia,Developing regions,1,1,6,1,2,4,13,...,607,540,511,581,561,1392,1129,1185,1308,20444
Oman,Asia,Western Asia,Developing regions,0,0,0,8,0,0,0,...,14,18,16,10,7,14,10,13,11,448
Pakistan,Asia,Southern Asia,Developing regions,978,972,1201,900,668,514,691,...,14314,13127,10124,8994,7217,6811,7468,11227,12603,483200
Philippines,Asia,South-Eastern Asia,Developing regions,6051,5921,5249,4562,3801,3150,4166,...,18139,18400,19837,24887,28573,38617,36765,34315,29544,1022782
Qatar,Asia,Western Asia,Developing regions,0,0,0,0,0,0,1,...,11,2,5,9,6,18,3,14,6,314
Republic of Korea,Asia,Eastern Asia,Developing regions,1011,1456,1572,1081,847,962,1208,...,5832,6215,5920,7294,5874,5537,4588,5316,4509,285162
Saudi Arabia,Asia,Western Asia,Developing regions,0,0,1,4,1,2,5,...,198,252,188,249,246,330,278,286,267,6850
Singapore,Asia,South-Eastern Asia,Developing regions,241,301,337,169,128,139,205,...,392,298,690,734,366,805,219,146,141,29158
Sri Lanka,Asia,Southern Asia,Developing regions,185,371,290,197,1086,845,1838,...,4930,4714,4123,4756,4547,4422,3309,3338,2394,296716
State of Palestine,Asia,Western Asia,Developing regions,0,0,0,0,0,0,0,...,453,627,441,481,400,654,555,533,462,13024
Syrian Arab Republic,Asia,Western Asia,Developing regions,315,419,409,269,264,385,493,...,1458,1145,1056,919,917,1039,1005,650,1009,62970
Tajikistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,0,...,85,46,44,15,50,52,47,34,39,1006
Thailand,Asia,South-Eastern Asia,Developing regions,56,53,113,65,82,66,78,...,575,500,487,519,512,499,396,296,400,18348
Turkey,Asia,Western Asia,Developing regions,481,874,706,280,338,202,257,...,2065,1638,1463,1122,1238,1492,1257,1068,729,63562
Turkmenistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,0,...,40,26,37,13,20,30,20,20,14,620
United Arab Emirates,Asia,Western Asia,Developing regions,0,2,2,1,2,0,5,...,31,42,37,33,37,86,60,54,46,1672
Uzbekistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,0,...,330,262,284,215,288,289,162,235,167,6736
Viet Nam,Asia,South-Eastern Asia,Developing regions,1191,1829,2162,3404,7583,5907,2741,...,1852,3153,2574,1784,2171,1942,1723,1731,2112,194292
Yemen,Asia,Western Asia,Developing regions,1,2,1,6,0,18,7,...,161,140,122,133,128,211,160,174,217,5970

<p>We can pass multiple criteria in the same line</p>

In [119]:
df_can[(df_can["Continent"] == "Asia") & (df_can["Region"] == "Southern Asia")]

,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,1986,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,496,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,117278
Bangladesh,Asia,Southern Asia,Developing regions,83,84,86,81,98,92,486,...,4171,4014,2897,2939,2104,4721,2694,2640,3789,131136
Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,...,5,10,7,36,865,1464,1879,1075,487,11752
India,Asia,Southern Asia,Developing regions,8880,8670,8147,7338,5704,4211,7150,...,36210,33848,28742,28261,29456,34235,27509,30933,33087,1383808
Iran (Islamic Republic of),Asia,Southern Asia,Developing regions,1172,1429,1822,1592,1977,1648,1794,...,5837,7480,6974,6475,6580,7477,7479,7534,11291,351846
Maldives,Asia,Southern Asia,Developing regions,0,0,0,1,0,0,0,...,0,0,2,1,7,4,3,1,1,60
Nepal,Asia,Southern Asia,Developing regions,1,1,6,1,2,4,13,...,607,540,511,581,561,1392,1129,1185,1308,20444
Pakistan,Asia,Southern Asia,Developing regions,978,972,1201,900,668,514,691,...,14314,13127,10124,8994,7217,6811,7468,11227,12603,483200
Sri Lanka,Asia,Southern Asia,Developing regions,185,371,290,197,1086,845,1838,...,4930,4714,4123,4756,4547,4422,3309,3338,2394,296716

<p><b>Exercise:</b> Fetch the data where AreaName is "Africa" and RegName is "Southern Africa". Display the dataframe and find out how many instances are there</p>

In [123]:
df_can[(df_can["Continent"] == "Africa") & (df_can["Region"] == "Southern Africa")]

,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,1986,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Botswana,Africa,Southern Africa,Developing regions,10,1,3,3,7,4,2,...,7,11,8,28,15,42,53,64,76,792
Lesotho,Africa,Southern Africa,Developing regions,1,1,1,2,7,5,3,...,4,0,4,1,8,7,1,0,6,214
Namibia,Africa,Southern Africa,Developing regions,0,5,5,3,2,1,1,...,6,19,13,26,14,16,23,24,83,640
South Africa,Africa,Southern Africa,Developing regions,1026,1118,781,379,271,310,718,...,988,1111,1200,1123,1188,1238,959,1243,1240,81136
Swaziland,Africa,Southern Africa,Developing regions,4,1,1,0,10,7,1,...,7,7,5,6,10,3,13,17,39,376

<h3><b>Sorting values of a DataFrame or series</b></h3>

<p>You can use the <b>sort_values()</b> function is used to sort a DataFrame or a Seires based on one or more columns</p>

In [128]:
df_can.sort_values(by="Total", ascending=False, axis=0, inplace=True)
top_5 = df_can.head(5)
top_5

,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,1986,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
India,Asia,Southern Asia,Developing regions,8880,8670,8147,7338,5704,4211,7150,...,36210,33848,28742,28261,29456,34235,27509,30933,33087,1383808
China,Asia,Eastern Asia,Developing regions,5123,6682,3308,1863,1527,1816,1960,...,42584,33518,27642,30037,29622,30391,28502,33024,34129,1319924
United Kingdom of Great Britain and Northern Ireland,Europe,Northern Europe,Developed regions,22045,24796,20620,10015,10170,9564,9470,...,7258,7140,8216,8979,8876,8724,6204,6195,5827,1103000
Philippines,Asia,South-Eastern Asia,Developing regions,6051,5921,5249,4562,3801,3150,4166,...,18139,18400,19837,24887,28573,38617,36765,34315,29544,1022782
Pakistan,Asia,Southern Asia,Developing regions,978,972,1201,900,668,514,691,...,14314,13127,10124,8994,7217,6811,7468,11227,12603,483200

<p><b>Exercise:</b> Find out top 3 countries that contirbutes the most to inmigration to Canada in the year 2010</p>

In [132]:
df_can.sort_values(by="2010", ascending=False, axis=0, inplace = True)
top3_2010 = df_can["2010"].head(3)
top3_2010

Philippines    38617
India          34235
China          30391
Name: 2010, dtype: int64

In [133]:
df_can["2010"].head(5)

Philippines                                             38617
India                                                   34235
China                                                   30391
United Kingdom of Great Britain and Northern Ireland     8724
United States of America                                 8142
Name: 2010, dtype: int64